export const GET_REQUEST="GET_REQUEST"
export const GET_SUCCESS="GET_SUCCESS"
export const GET_ERROR="GET_ERROR"

export const ADD_REQUEST="ADD_REQUEST"
export const ADD_SUCCESS="ADD_SUCCESS"
export const ADD_ERROR="ADD_ERROR"

export const DELETE_REQUEST="DELETE_REQUEST"
export const DELETE_SUCCESS="DELETE_SUCCESS"
export const DELETE_ERROR="DELETE_ERROR"

export const UPDATE_REQUEST="UPDATE_REQUEST"
export const UPDATE_SUCCESS="UPDATE_SUCCESS"
export const UPDATE_ERROR="UPDATE_ERROR"